# Generated by Django 3.1 on 2020-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20200805_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
