# Generated by Django 3.1 on 2020-08-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_stickynote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='zIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
