# Generated by Django 3.1 on 2020-08-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_stickynote_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='slug',
            field=models.SlugField(default='hello-world'),
            preserve_default=False,
        ),
    ]
